# sys/xbin/sh
clear



# <!------------------------------------------->
NOCOLOR='\033[0m'
RED='\033[1;31m'
GREEN='\033[1;32m'
ORANGE='\033[1;33m'
BLUE='\033[1;34m'
PURPLE='\033[1;35m'
CYAN='\033[1;36m'
LIGHTGRAY='\033[1;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'
# <!------------------------------------------->




# <!------------------------------------------->
echo "${CYAN}╾╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╼"
echo "${WHITE}        CHECKSUM HASH CHECKER FREE"
echo "${CYAN}╾╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╼"
echo "${CYAN}Created By ${GREEN}: ${YELLOW}Sahrul Gunawan Cyber"
echo "${CYAN}License By ${GREEN}: ${YELLOW}Defender Tools LTD"
echo "${CYAN}Realese    ${GREEN}: ${YELLOW}10-JUNI-2023"
echo "${CYAN}Support Os ${GREEN}: ${YELLOW}Linux , Ubuntu , More"
echo "${CYAN}Support Regex ${GREEN}: \n-> ${YELLOW}Example , *.css , *.* , h.* More"
echo "${CYAN}╾╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╼"
echo "${CYAN}1. Select ${GREEN}: ${YELLOW}Default Mirror "
echo "${CYAN}1. Select ${GREEN}: ${YELLOW}Other Mirror Tools"
echo "${CYAN}╾╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╼"
echo "${WHITE}"
# <!------------------------------------------->
read -p "[+] Input Files Name ~> " input;

echo "SHA1SUM"
sha1sum $input > 1output.txt && sleep 1 && cat 1output.txt | cut -d ' ' -f 1 | sort -r
echo
echo "SHA224SUM"
sha224sum $input > 2output.txt && sleep 1 && cat 2output.txt | cut -d ' ' -f 1 | sort -r
echo
echo "SHA256SUM"
sha256sum $input > 3output.txt && sleep 1 && cat 3output.txt | cut -d ' ' -f 1 | sort -r
echo
echo "SHA384SUM"
sha384sum $input > 4output.txt && sleep 1 && cat 4output.txt | cut -d ' ' -f 1 | sort -r
echo
echo "SHA512SUM"
sha512sum $input > 5output.txt && sleep 1 && cat 5output.txt | cut -d ' ' -f 1 | sort -r

echo
echo "OPENSSL VERSION SHA512SUM"
openssl dgst -sha256 $input > 6output.txt && sort 6output.txt
#------------( Full Checksum Files )----------
echo
echo "${YELLOW}FULL CHECK CHECKSUM"
echo "${CYAN}╾╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╼"
echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -blake2b512 $input > 7output.txt && sort 7output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -blake2s256 $input > 8output.txt && sort 8output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -md4 $input > 9output.txt && sort 9output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -md5 $input > 10output.txt && sort 10output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -mdc2 $input > 11output.txt && sort 11output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -rmd160 $input > 12output.txt && sort 12output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha1 $input > 13output.txt && sort 13output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha224 $input > 14output.txt && sort 14output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha256 $input > 15output.txt && sort 15output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha3-224 $input > 16output.txt && sort 16output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha3-256 $input > 17output.txt && sort 17output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha3-384 $input > 18output.txt && sort 18output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha3-512 $input > 19output.txt && sort 18output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha384 $input > 20output.txt && sort 20output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha512 $input > 21output.txt && sort 21output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha512-224 $input > 22output.txt && sort 22output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sha512-256 $input > 23output.txt && sort 23output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -shake128 $input > 24output.txt && sort 24output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -shake256 $input > 25output.txt && sort 25output.txt

echo
echo "${YELLOW}Generated By Openssl CheckSum${CYAN}"
openssl dgst -sm3 $input > 26output.txt && sort 26output.txt


echo "${CYAN}╾╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╴╼"
rm -rf 1output.txt 2output.txt 3output.txt 4output.txt 5output.txt 6output.txt 7output.txt 8output.txt 9output.txt 10output.txt 11output.txt 12output.txt 13output.txt 14output.txt 15output.txt 16output.txt 17output.txt 18output.txt 19output.txt 20output.txt 21output.txt 22output.txt 23output.txt 24output.txt 25output.txt 26output.txt
